@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> Main: Start program
Main -> Service: logIn(username, password)
Service -> User: validate(username, password)
User --> Service: true/false
Service --> Main: "Login successful" or "Login failed"
@enduml