@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

object Streamingplatform
object User
object Startmenu
object Mainmenu
object Media
object Movies
object Series
object Season
object Episode


Streamingplatform *-- Startmenu
Startmenu *-- User
Startmenu *-- Mainmenu
Mainmenu *-- User
Mainmenu *-- Media
Media <|-- Movies
Media <|-- Series


Streamingplatform *-- User

Series *-- Season
Season *-- Episode






@enduml